sudo: required
dist: trusty

language: ruby

rvm:
  - 2.2.3

nvm:
  - 4.1.2

before_install:
 - gem install bundler

install:
 - bash scripts/dep-i.sh

before_script:
 - bash emoji.sh

script: gulp --gulpfile scripts/build.js

branches:
  only:
    - master